19 add notification display option
hexlet-codebattle/chrome_extension pull request #35
Opened 2020-10-03 20:22 UTC by H9ko

#19

2020-10-03 20:26 UTC, H9ko commented
Поправлен баг двойного вызов onUpdate из за лишней подписки

2020-10-03 22:22 UTC, BabayevEldar requested changes

2020-10-03 22:22 UTC, BabayevEldar commented on src/background/browser-actions.js
> +const displayNotification = () => {
Я бы имя поменял с _displayNotification_ на _setNotification_

2020-10-05 00:28 UTC, glagius requested changes

2020-10-05 00:28 UTC, glagius commented on src/background/browser-actions.js
>      if (storage.toggles.notification) {
Давай переключатели назовём явно? 
showNotoficationsOnChanges ? Или что-то в этом роде.
Сейчас ощущение что там может лежать что угодно а не просто булеан

2020-10-05 17:48 UTC, H9ko commented on src/background/browser-actions.js
>      if (storage.toggles.notification) {
Ну я себе представлял что мы на следующем этапе создадим файл с отдельными объектами options (новая игра, новый турнир и тд) для notification и будет их передавать в эту функцию . что то типа 
const newGame = {
  type: 'basic',
  message: 'New game availible',
  title: 'Codebattle ',
  iconUrl: '../assets/128.png',
  eventTime: 23,
  buttons: [
    {
      title: 'Close button',
    },
    {
      title: 'Join button',
    },
  ],
}
displayNotification(newGame)
displayNotification(newTournament)

2020-10-05 23:44 UTC, glagius commented on src/background/browser-actions.js
>      if (storage.toggles.notification) {
Так речь про настройки экстеншена. 
Там у нас просто переключатели вкл/выкл

2020-10-11 06:06 UTC, H9ko commented
Я как завершу напишу, проверял правильно ли смержил

2020-10-11 15:57 UTC, glagius approved these changes

2020-10-11 15:57 UTC, glagius commented on src/background/notifications.js
> +export default { newGame, opponentJoin, newTournament };
Мне кажется, или тут экспорт специфический получился?

2020-10-11 15:57 UTC, merged