remake newGame notification, add join button
hexlet-codebattle/chrome_extension pull request #43
Opened 2020-10-12 10:39 UTC by H9ko

#19

2020-10-12 11:01 UTC, glagius requested changes

2020-10-12 11:01 UTC, glagius commented on src/background/state.js
> +      const message = `Player - ${action.payload.players[0].name} || game level - ${action.payload.level} || status - ${action.payload.state} `;
Вот эта строка мне кажется не должна зависеть от кол-ва игроков. Это больше придирки, но тут информация по игре, и отдельно - статус игры.

2020-10-12 11:12 UTC, H9ko commented on src/background/browser-actions.js
> +      const popupNotification = new Notification(id.toString(), currentNotification);
Ну типа в дефолтном уведомление заменить нужное, как лучше сделать видишь?

2020-10-12 11:14 UTC, H9ko commented on src/background/state.js
> +      const message = `Player - ${action.payload.players[0].name} || game level - ${action.payload.level} || status - ${action.payload.state} `;
Где- то про это общались в игре может быть только 2 игрока и players[0] всегда создатель
Если строку делать независимой я не узнаю имя создателя

2020-10-12 11:21 UTC, glagius commented on src/background/browser-actions.js
> +      const popupNotification = new Notification(id.toString(), currentNotification);
Ну вот смотри.
1. Я специально создал файл с моделями, чтобы держать там все шаблоны, и т.п.
2. Есть класс Уведомление, у которого есть дефолтный шаблон. Ты можешь поправить реализацию класса, чтобы он получал шаблон и данные которые надо отобразить.
3. В идеале, надо чтобы у нас была очередь сообщений, не больше Н числа. И обновляются они по принципу стека.

2020-10-12 12:22 UTC, H9ko commented on src/background/browser-actions.js
> +      const popupNotification = new Notification(id.toString(), currentNotification);
Что есть очередь сообщений? и зачем она? У нас уникальные ID

2020-10-12 13:04 UTC, glagius commented on src/background/browser-actions.js
> +      const popupNotification = new Notification(id.toString(), currentNotification);
очереди пока нет. Это была "преждевременная оптимизация"

2020-10-12 17:15 UTC, H9ko commented
Переделал на функцию, но возникли проблемы с addListener которые создавались каждый раз и множились. Пришлось сделать логику по их очищению. Есть сомнения что перемудрил

2020-10-13 07:58 UTC, glagius requested changes
Т.к. объект "notifications" глобальный, то и вотчеры надо делать в одном месте, а не на каждый чих. 
Лучше сделать отдельно обработчик кликов, и слушать это событие (  browser.notifications.onButtonClicked.addListener(handleOnButtonClicked); ) в index.js

2020-10-13 07:58 UTC, glagius commented on src/background/browser-actions.js
> +      createNotification(gameID.toString(), notifications[notification], message, gameID);
Может вместо notifications будет templates ?

2020-10-13 16:50 UTC, H9ko commented
У меня вложенность из за того что внутренний обработчик должен имень доступ к переменным
Типа вынесу наверх и сделаю единый листенер на все кнопки я не смогу узнать какой именно отработал кроме id и индекса кнопки не возвращается никакой инфы

2020-10-13 19:06 UTC, H9ko commented on src/background/browser-actions.js
> +      createNotification(gameID.toString(), notifications[notification], message, gameID);
templates разве сам по себе ничего не дает как информацию?, templateNotifications но длинно получается

2020-10-13 19:14 UTC, H9ko commented
Переделал на советы сделать один/общий листенер, через хак передачи через ID

2020-10-13 19:31 UTC, H9ko commented
Starting your workflow run...
Github Actions не работает , гугл говорит не правильно просано/нравится версию убунту и матрикс ишью создать отдельный?

2020-10-14 02:53 UTC, merged